### ISSUE TITLE
Delete pytorch dependencies in pointconv_utils.py

### ISSUE THREAD

**Issue by heiwang1997** [Jittor/PointCloudLib#5]
Hi,

It would be good if you could delete pytorch usages in `misc/pointconv_utils.py`, such as this one:
https://github.com/Jittor/PointCloudLib/blob/6a8f5d0d8bdf9856ea577f182800a29a1cd64e2f/misc/pointconv_utils.py#L243

Best

**Comment by MenghaoGuo** [comment]
Thanks for Jiahui's advice.
I will delete it now.
